#comprehensive-degisn
spring:
  application:
    name: comprehensive-design
  datasource:
    url: jdbc:mysql://localhost:3306/comprehensive-degisn
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: @YOUR_PASSWORD@
  jpa:
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
